import Header from "@/components/layouts/header"
import CareersHero from "@/components/sections/careers/careers"
import CareersForm from "@/components/sections/careers/careersForm"
import Studio from "@/components/sections/studio/studio";
import CTA from "@/components/sections/cta/cta";
import Footer from "@/components/layouts/footer"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Join Our Team",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main>

      <Header />
      <CareersHero />
      <div
        className="
          relative 
          z-20 
          -mt-10 md:-mt-12
          bg-white md:bg-[#f5f5f5]
          rounded-t-[20px] md:rounded-t-[30px]
          pt-12 md:pt-16
        "
      >
        <CareersForm />
        <Studio />
        <CTA />
      </div>
      <Footer />

    </main>
  )
}