import Header from "@/components/layouts/header"
import Contact from "@/components/sections/contact/contact"
import CTA from "@/components/sections/cta/cta";
import Footer from "@/components/layouts/footer"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main>

      <Header />
      <Contact />
      <CTA />
      <Footer />

    </main>
  )
}