import Header from "@/components/layouts/header"
import TeamHero from "@/components/sections/team/team"
import FounderSection from "@/components/sections/team/founderSection"
import TeamSection from "@/components/sections/team/teamSection"
import JoinTeamCTA from "@/components/sections/team/joinTeamCTA"
import Footer from "@/components/layouts/footer"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Join Our Team",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main>

      <Header />
      <TeamHero />
      <FounderSection />
      <TeamSection />
      <JoinTeamCTA />
      <Footer />

    </main>
  )
}