import Header from "@/components/layouts/header"
import TeamHero from "@/components/sections/team/team"
import FounderSection from "@/components/sections/team/founderSection"
import StorySection from "@/components/sections/team/story"
import TeamSection from "@/components/sections/team/teamSection"
import JoinTeamCTA from "@/components/sections/team/joinTeamCTA"
import Footer from "@/components/layouts/footer"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Join Our Team",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main>

      <Header />
      <TeamHero />
      <div
        className="
          relative 
          z-20 
          -mt-10 md:-mt-6
          bg-white md:bg-white 
          rounded-t-[20px] md:rounded-t-[30px]
          pt-12 md:pt-16
        "
      >
        <FounderSection />
        <StorySection />
        <TeamSection />
        <JoinTeamCTA />
      </div>
      <Footer />

    </main>
  )
}