import Header from "@/components/layouts/header"
import VipHero from "@/components/sections/vip/vip"
import VipFeatures from "@/components/sections/vip/vipFeatures"
import VipForm from "@/components/sections/vip/vipForm"
import Studio from "@/components/sections/studio/studio";
import CTA from "@/components/sections/cta/cta";
import Footer from "@/components/layouts/footer"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ammache VIP",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main>

      <Header />
      <VipHero />
         <div
        className="
          relative 
          z-20 
          -mt-10 md:-mt-12
          bg-white md:bg-white 
          rounded-t-[20px] md:rounded-t-[30px]
          pt-12 md:pt-16
        "
      >
      <VipFeatures />
      <VipForm />
      <Studio />
      <CTA />
      </div>
      <Footer />

    </main>
  )
}